surname = input("surname: ")
first_name = input("First name: ")
street = input("Street: ")
number = input("Number: ")
zip_code = input("Zip code: ")
city = input("City: ")

print(first_name,surname)
print(street,number)
print(zip_code,city)